# 服务配置
server:
  port: 21090
  servlet:
    context-path: /api/personal-heath/v1.0
# API地址前缀，用于接口拦截放行
my-server:
  api-context-path: /api/personal-heath/v1.0
#MySQL与文件上传限制配置
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_health?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
# 让 Mybatis 在 Mapper目录下找到 XML 映射文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
# MyBatis-Plus 配置（可选，根据需求添加）
mybatis-plus:
  # 1. 配置 Mapper 接口的 XML 文件路径（若用注解式 SQL 可省略）
  mapper-locations: classpath:mapper/**/*.xml # 示例：XML 文件放在 resources/mapper 目录下
  # 2. 配置实体类包路径（MP 自动扫描该包下的实体类，用于别名、表映射等）
  type-aliases-package: com.example.demo.entity # 替换为你的实体类包名
  # 4. 日志配置（可选，开发环境开启 SQL 日志，方便调试）
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




